---
title: "Population Data Management"
author: "Alicia Rich"
output:
  html_document:
    theme:
      bootswatch: litera
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: true
    code_folding: "show"
    fig_caption: true
    df_print: paged
params:
  course: "zoobio"
  semester: "spring25"
                     
---

```{r, include = FALSE}
global             <- config::get(config = "default")
here::i_am("assignments/zoobio/labs/PopulationData.Rmd")
source(here::here(global$setup))

theme_set(theme_classic())
thematic_rmd()
thematic_on(accent = "#8785B2FF", fg = "black")

opts_chunk$set(message = FALSE,
               warning = FALSE,
               echo    = FALSE,
               include = TRUE,
               eval    = TRUE,
               comment = "")

source(here(paste0(course$labs, "ImportStudbooks.R")))
source(here(paste0(course$labs, "PedigreeFunctions.R")))
```

```{r, warning = FALSE}
studbook <- read_studbook_historic(here(paste0(course$assignments, "/testing/StudbookPSL2021Historic.csv"))) %>%
  full_join(read_studbook_current(here(paste0(course$assignments , "/testing/StudbookPSL2024Living.csv")))) %>%
  full_join(read_studbook_current(here(paste0(course$assignments , "/testing/StudbookPSL2021Living.csv"))))   %>%
  format_studbook(sex_unknown = 0) %>%
  sub_missing_parents()  %>%
  mutate(across(where(is.numeric), ~ replace_na(., 0)))
```

```{r}
pedig <- ped(
  id     = studbook$ID,
  fid    = studbook$Sire,
  mid    = studbook$Dam,
  sex    = studbook$Sex
) %>% parentsBeforeChildren() %>% foundersFirst()
```

```{r}
founders    <- founders(pedig)
nonfounders <- nonfounders(pedig)

deceased    <- filter(studbook, status != "alive") %>% 
  select(ID) %>% 
  deframe() %>%
  setdiff(founders)

female      <- filter(studbook, status == "alive") %>% 
  select(ID) %>% 
  deframe() %>%
  intersect(nonfounders(pedig)) %>% 
  intersect(females(pedig))

male      <- filter(studbook, status == "alive") %>% 
  select(ID) %>% 
  deframe() %>%
  intersect(nonfounders(pedig)) %>% 
  intersect(males(pedig))

undet <- nonfounders(pedig) %>% 
  setdiff(females(pedig)) %>% 
  setdiff(males(pedig)) %>% 
  setdiff(deceased)

fills         <- list(
  "#A5AA99FF" = c(deceased),
  "#DAA51BFF" = c(founders),
  "#CC61B0FF" = c(female),
  "#2F8AC4FF" = c(male),
  "#99C945FF" = c(undet)
)
```

```{r}
pedig.max   <- get_biggest_ped(pedig)
pedig.minor <- get_minor_peds(pedig)

twins.include <- subset_twins(studbook, pedig.max)
twins.list    <- twins_vector(twins.include)
```


```{r}
  plot(pedig.max,
       cex      = 0.5,
       labs     = NULL,
       deceased = deceased,
       fill     = fills,
       col      = "black",
       twins    = twins.include)
```


Calculating a kinship matrix across all pairs of individuals

First we need to convert to kinship2 pedigree format

```{r}
all.twins <- subset_twins(studbook, pedig)
```

```{r}
studbook.kin <- studbook %>%
  mutate(status = if_else(status != "alive", 1, 0),
         Sex    = if_else(Sex == 0, 3, Sex))
```


```{r}
pedig.kin <- pedigree(
  id       = studbook.kin$ID,
  dadid    = studbook.kin$Sire,
  momid    = studbook.kin$Dam,
  sex      = studbook.kin$Sex,
  status   = studbook.kin$status,
  relation = as.matrix(all.twins)
)
```

```{r}
kinship_all <- kinship(pedig.kin)
```

Now let's subset that for only the living individuals

```{r}
living         <- filter(studbook, status == "alive") %>% select(ID) %>% deframe()
living.kin     <- intersect(living, rownames(kinship_all))

kinship_living <- kinship_all[living.kin, living.kin]
```

KappaIBD requires that we use the original pedtools format of pedigree.

```{r}
kappa_all <- kappaIBD(pedig)
```

```{r}
kappa_living <- filter(kappa_all, id1 %in% living.kin & id2 %in% living.kin)
```


