---
title: "PopulationManagementOverview"
author: "Alicia Rich"
date: "2025-03-09"
output: html_document
---


# Background

## Studbook Data Field Descriptions

**Studbook ID**

- Unique number assigned to each individual in the studbook. 
  - The studbook number is a permanent number.

**GAN**

- Global Accession Number; unifying *key record* under which all animal data for that individual is tracked.

**Current Location**

- Indicates the current location of a living animal or the last known location of a dead/LTF/released individual.

**Current Local ID**

- Indicates the individual’s local ID identifier at its current holding institution if living, or its local ID identifier at its last known holding institution if dead/LTF/released.

**Sex**

- Male, female, undetermined.

**Birth/Hatch Date**

- This field indicates the date of an animal’s birth/hatch. 
  - There is a birth/hatch date for every individual. 
  - If there is any estimate surrounding this date, it will be reflected in this field.

**Current Status**

- Indicates whether the individual is living, dead, released, undetermined (`LTF`), etc.

**Sire/Dam**

- Numbers reported in this field indicate the Studbook ID of an animal’s parents, when those parents are known. 
  - `WILD` indicates that an animal was wild- caught and its parents are unknown, wild individuals. 
  - `UND` indicates that the parentage of that animal is undefined. 
  - `MULTX`, where `X` is a number, indicates that there are several possible parents, but the specific parent could not be determined. 
    - The possible parents within any given `MULT` are tracked within ZIMS and will be listed when you expand the `Parent` field for that individual.

**Age**

- If individual is still alive, this number indicates age of individual at time of data export.
- If individual is no longer alive/tracked in the SB, indicates age at time of death/LTF/release.

**Birth/Hatch Type**

- Indicates whether the individual was born/hatched in the wild or a captive environment.
  - Undetermined indicates the birth/hatch type is not known.

**Event Type**

- This field documents the movements (i.e. transactions) of individual animals from the first location to the current or last known location. 
  - This includes:
    - `Birth/Hatch`
    - `Transfer`
    - `Death`
    - `Go LTF` (*Lost to Follow up*)
    - `Return from LTF`
    - `Release`
    
**Date**

- This field documents the date that any given event occurred.
  - Each event has a date associated with it. 
  - If there is any estimate surrounding this date it will be reflected in this field.

**Location**

- This field indicates the location where the event took place.
- *Undetermined* indicates that the animal exists or existed, but its location cannot be reliably confirmed. 

**Local ID**

- This is the number assigned by the institution in which the event took place. 
- `-` indicates that either an ID was not assigned or no information exists to indicate that an ID was assigned.

**House Name**

- This field indicates the name given to the animal at a specific location. 
  - *Individuals may be given a different house name each time they move to a different location.*
  
## PMC's BTP Metrics

### Demographic Terms

#### Age Distribution

A visual representation of the numbers or percentages of individuals in various age and sex classes.

#### Lambda () or Population Growth Rate

The proportional change in population size from one year to the next. A lambda of 1.11 means an 11% per year increase; a lambda of 0.97 means a 3% decline in size per year. The three lambdas highlighted in this BTP are: 1) Life Table, from the PMx life tables, the change in the population based on the demographic regional and date window exported from the studbook, the life table lambda is the rate at which the population would be expected to grow (in the future) given the birth and death rates reported in the life tables and assuming a stable age distribution (does NOT factor in imports or exports); 2) 5-year, from the studbook census, the 5-year lambda is calculated from observed changes in population size over the last 5 years and includes births, deaths, imports and exports; and 3) Projected, from the PMx stochastic 20-year projections (includes confidence intervals), models how the population is predicted to grow or decline over the next 20 years given the birth and death rates from the life tables and the age structure of the current population.

Lx, Age-Specific Survivorship

The probability that a new individual (e.g., age 0) is alive at the beginning of age x. Alternatively, the proportion of individuals which survive from birth to the beginning of a specific age class.

Mean Generation Time (T)

The average time elapsing from reproduction in one generation to the time the next generation reproduces. Also, the average age at which a female (or male) produces offspring. It is not the age of first reproduction. Males and females often have different generation times.

Median Life Expectancy (MLE)

The ‘typical’ age at which an average animal is expected to live; 50% will die before the median life expectancy and 50% die after. The MLE reported in Breeding and Transfer Plans (BTPs) and Survival Stats Reports, does exclude individuals that did not survive to their first birthday. The MLE obtained from population management software (PM2000, PMx, ZooRisk) or from life tables in BTPs (e.g., where Lx = 0.5) will be lower because they include those individuals that did not survive to their first birthday in order to project the correct number of births needed. A Survival Statistics Library is maintained for most AZA Animal Programs on the AZA website: https://www.aza.org/species-survival-statistics.

Maximum Longevity

The maximum age at which we have observed a species to live. If the oldest observed animal is currently living, we do not yet know the maximum longevity.

Mx, Fecundity

The average number of same-sexed offspring born to animals in that age class. Because studbooks typically have relatively small sample sizes, studbook software calculates Mx as 1/2 the average number of offspring born to animals in that age class. This provides a somewhat less "noisy" estimate of Mx, though it does not allow for unusual sex ratios. The fecundity rates provide information on the age of first, last, and maximum reproduction.

Px, Age-Specific Survival

The probability that an individual of age x survives an age class; is conditional on an individual being alive at the beginning of the age class. Alternatively, the proportion of individuals that survive from the beginning of one age class to the next.
Qx, Mortality – The probability that an individual of age x dies during an age class (Qx = 1-Px). Alternatively, the proportion of individuals that die during an age class. It is calculated from the number of animals that die during an age class divided by the number of animals that were alive at the beginning of the age class (i.e., "at risk").

Risk (Qx or Mx)

The number of individuals that have lived during an age class. The number “at risk” is used to calculate Mx and Qx by dividing the number of births and deaths that occurred during an age class by the number of animals at risk of dying and reproducing during that age class.

Genetic Terms

Effective Population Size (Ne)

The size of a randomly mating population of constant size with equal sex ratio and a Poisson distribution of family sizes that would (a) result in the same mean rate of inbreeding as that observed in the population, or (b) would result in the same rate of random change in allele frequencies (genetic drift) as observed in the population. These two definitions are identical only if the population is demographically stable (because the rate of inbreeding depends on the distribution of alleles in the parental generation, whereas the rate of allele frequency drift is measured in the current generation). More specifically, PMx software use the definition as the size of the current population that has produced offspring, assuming that there are current breeders, that these current breeders have a Poisson distribution of family sizes, that none of the current breeders are now post-reproductive, and none of the not-yet-breeding adults will breed.

Founder

An individual obtained from a source population (often the wild) that has no known relationship to any individuals in the derived population (except for its own descendants).

Founder Genome Equivalents (FGE)

The number of wild-caught individuals (founders) that represent the same amount of gene diversity as does the population under study. The gene diversity of a population is 1 - 1 / (2 * FGE).

Founder Representation

The proportion of the alleles in the living, descendant population that are derived from that founder.

Gene Diversity (GD)

The probability that two alleles randomly sampled from the same genetic locus across a population are not identical by descent. Gene diversity is calculated relative to a population’s founders, which are assumed to be unrelated and not inbred, and is the proportional diversity retained by the current, descendant population.

Inbreeding Coefficient (F)

The probability that the two alleles present at an individual’s genetic locus are identical by descent (i.e., both alleles originated from an ancestor common to both the individual’s parents).

Mean Kinship (MK)

The mean (or average) kinship coefficient between an animal and all animals (including itself) in the living, zoo/aquarium population. An individual’s mean kinship is a measure of how well its alleles are represented within a population. Animals with low mean kinships have few relatives, are from under-represented founder lineages, and have transmitted few of their alleles to the next generation; these individuals should be prioritized for breeding to slow a population’s gene diversity loss.

Percent Known

The percentage of an animal's genome that is traceable to known founders. Thus, if an animal has an UNK sire, its % Known = 50. If it has an UNK grandparent, its % Known = 75.

Percent Certain

The percentage of the living individuals’ pedigree that can be completely identified as certain: (exact identity of both parents is known) and traceable back to known founders. Individuals that are 100% certain do not have any MULTs or UNKs in their pedigree. Certainty represents a higher degree of knowledge than Known and therefore is always less than or equal to Known.

Management Terms

Signature Species Survival Plan® (Signature SSP) Program

A Signature SSP Program is a population that is considered to be sustainable using robust measures of viability and sustainability defined by the AZA Animal Population Management Committee. A Signature SSP meets all of the requirements to become an SSP, and scores at least two positives and does not score any negatives in the SSP Assessment process.

Provisional Species Survival Plan® (Provisional SSP) Program

A Provisional SSP Program is a population that is a priority for AZA members but does not currently meet the definitions of viability and sustainability defined by the AZA Animal Population Management Committee. A Provisional SSP Program meets all of the requirements to become an SSP and does not score a negative in more than two categories in the SSP Assessment process.

Sustainability Partners

AZA Animal Population Management (APM) Committee approved wildlife facilities that regularly exchange animals with AZA-accredited facilities and certified related facilities, typically as part of the Species Survival Plan® (SSP) Program Breeding and Transfer Plan or other SSP Program management process.

Animal Program Engagement

AZA policy stating that all AZA accredited are committed to managing robust animal populations in zoos and aquariums to assure that animals are available to meet individual program goals and fulfill our collective mission. Successful population management relies on highly collaborative, communicative, and engaged relationships among AZA members and Animal Programs (i.e., Taxon Advisory Groups (TAGs), Species Survival Plans® (SSPs), and AZA Studbooks). Therefore, all AZA member facilities must fully engage with and participate in each SSP that pertains to an animal that the facility own or is part of their collection. Further, each Animal Program Leader (i.e., TAG Chair, SSP Coordinator, and Studbook Keeper) must fully engage with each facility that is part of their Animal Program. Animal Program engagement is defined and explained in the Facility Handbook on Animal Program Engagement and with the SSP and TAG Handbooks (See Appendix G for link to additional AZA Policies pertinent to population management).

Target Population Size (TPSDATE)

A short-term target number of animals that is realistic yet aspirational, to be reached by the program by a specified target date. Factors considered when setting TPS may include program goals, the CPS/CPT, logistical constraints, the trajectory and performance of the population, species biology/life history, and/or, where relevant, a desire to move the population size closer to the APS. The TPS should always be reported with a target date (e.g. TPS2029).

Commitment Population Size (CPSDATE) or Trend (CPTDATE)

A number OR trend in number of animals projected to be in a program by a specified short-term date, based solely on realistic participant commitment to holding the species. CPS/CPT should always be reported with a target date (e.g., CPS2029). CPS is a number that represents the size the population would be on that date if all realistic commitment to hold the taxon were filled and requests for acquisition/disposition completed. The unit for CPS may be “individuals” or an alternative unit appropriate to the taxon (e.g., “tanks”). Alternatively, CPT is the direction that the population is projected to shift, based on realistic commitment (growing, declining, remaining stable). CPS/CPT do not include biological/husbandry limitations, which are accounted for when setting TPS. TAGs are responsible for identifying the CPS or CPT and these values should be found in a Regional Collection Plan.

Advised Population Size (APS)

a scientifically derived size that, if the population reaches that size and maintains appropriate demographic and genetic characteristics, would result in a high likelihood of the population being robust, viable, healthy, and biologically sound.
